export enum AuthType {
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_CHECK = 'AUTH_CHECK',
  AUTH_ERROR = 'AUTH_ERROR',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_GET_PERMISSIONS = 'AUTH_GET_PERMISSIONS'
}

export enum RestType {
  GET_LIST = 'GET_LIST',
  GET_ONE = 'GET_ONE',
  GET_MANY = 'GET_MANY',
  GET_MANY_REFERENCE = 'GET_MANY_REFERENCE',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
  CUSTOM = 'CUSTOM'
}

export enum FetchStatus {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
